steps:
  - name: 'gcr.io/$PROJECT_ID/android:28'
    id: clean
    args: ["for_branch", "master", "./gradlew", "clean"]
  - name: 'gcr.io/$PROJECT_ID/android:28'
    id: test
    args: ["for_branch", "master", "./gradlew", "test"]
  - name: 'gcr.io/$PROJECT_ID/android:28'
    id: assemble
    args: ["for_branch", "master", "./gradlew", "assemble"]