steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'ls -la']
  - name: gradle:5.4.1-jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:5.4.1-jdk8
    entrypoint: gradle
    args: ["assemble"]